# Generated by Django 5.2.3 on 2025-07-16 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_news_per_day', models.IntegerField(default=0, help_text='Maximum number of news articles to reveive daily for this topic.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(related_name='topics_using_this_keyword', to='daily_news.keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Topic',
                'verbose_name_plural': 'User Topics',
                'ordering': ['user__username', '-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
