# Generated by Django 5.2.3 on 2025-06-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('target_words', models.CharField(max_length=100)),
                ('amount_of_news', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(verbose_name='creation date')),
                ('topic_description', models.CharField(max_length=200)),
            ],
        ),
    ]
