# Generated by Django 5.2.1 on 2025-05-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_news', '0002_topic_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
